### ISSUE TITLE
Install for organization?

### ISSUE THREAD

**Issue by splitbrain** [NikkelM/Todo-PR-Checker#63]
It seems it's not possible to install this app for an organization? Or am I missing something?

**Comment by NikkelM** [comment]
Hi, you're right, at the moment I do not publicly allow installing the app for organizations, as that has the potential to significantly increase traffic and thereby costs to maintain the app.
Normally I would add a separate pricing plan to the app that allows covering my costs, but unfortunately GitHub only allows adding paid plans if enough app installations have been reached.

If you are still interested in adding the app to your organization, we could discuss alternatives, such as me providing your organization with a private app instance, kept active during a sponsorship of the project. If you are interested, drop me a message at [nikkelm.dev@gmail.com](mailto:nikkelm.dev@gmail.com).

**Comment by splitbrain** [comment]
Thanks a lot for the offer. I am using phntmxyz/pr_todo_checker now. Since I only need it for a single repo that's the simplest solution.
